version: '3.8'

services:
  forgeweb:
    build:
      context: ..
      dockerfile: ops/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount content directory for persistence
      - ./content:/app/content
      - ./articles:/app/articles
      - ./assets:/app/assets
      # Optional: mount custom configuration
      - ./admin/site-config.json:/app/admin/site-config.json
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ops/ssl:/etc/ssl/certs:ro
    depends_on:
      - forgeweb
    restart: unless-stopped
    profiles:
      - production

  # Optional: Database for analytics (if needed)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=forgeweb
      - POSTGRES_USER=forgeweb
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - database

volumes:
  postgres_data:

# Networks for service isolation
networks:
  default:
    driver: bridge